import pyautogui as pag

input(f'Place cursor over transmute then hit enter')
transPos = pag.position()
print(f'Transmute coordinates are {transPos}')
input(f'Place cursor over augment then hit enter')
augPos = pag.position()
print(f'Augment coordinates are {augPos}')
input(f'Place cursor over Alteration then hit enter')
altPos = pag.position()
print(f'Alteration coordinates are {altPos}')
input(f'Place cursor over Regal then hit enter')
regalPos = pag.position()
print(f'Regal coordinates are {regalPos}')
input(f'Place cursor over scour then hit enter')
scourPos = pag.position()
print(f'Scour coordinates are {scourPos}')
input(f'Place cursor over exalt then hit enter')
exaltPos = pag.position()
print(f'Exalt coordinates are {exaltPos}')
input(f'Place cursor over item showcase in currency tab then hit enter')
stashPos = pag.position()
print(f'Stash coordinates are {stashPos}')
